# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: deadstock-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: deadstock_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:password@localhost:27017/deadstock_db --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  nodejs-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGODB_URI: "mongodb://admin:password@mongodb:27017/deadstock_db?authSource=admin"
      OPENAI_API_KEY: "YOUR_API_KEY_HERE" # Replace with your actual OpenAI API key
      FRONTEND_URL: "http://localhost:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    command: npm run dev

  nextjs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    depends_on:
      - nodejs-backend

volumes:
  mongodb_data: